sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
install:
  - npm install -g gulp-cli
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: gulp
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - google-chrome-stable
after_success:
  - bash <(curl -s https://codecov.io/bash)
